# Generated by Django 6.0.4 on 2026-05-01 02:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo', models.CharField(choices=[('mestre', 'Mestre'), ('player', 'Player')], default='player', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('mestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('idade', models.CharField(blank=True, max_length=20)),
                ('altura', models.CharField(blank=True, max_length=20)),
                ('peso', models.CharField(blank=True, max_length=20)),
                ('raca', models.CharField(blank=True, max_length=50)),
                ('forca', models.IntegerField(default=0)),
                ('destreza', models.IntegerField(default=0)),
                ('constituicao', models.IntegerField(default=0)),
                ('inteligencia', models.IntegerField(default=0)),
                ('sabedoria', models.IntegerField(default=0)),
                ('carisma', models.IntegerField(default=0)),
                ('vida', models.IntegerField(default=0)),
                ('energia', models.IntegerField(default=0)),
                ('sanidade', models.IntegerField(default=0)),
                ('armadura', models.IntegerField(default=0)),
                ('atk1', models.CharField(blank=True, max_length=100)),
                ('pts1', models.CharField(blank=True, max_length=20)),
                ('dano1', models.CharField(blank=True, max_length=100)),
                ('atk2', models.CharField(blank=True, max_length=100)),
                ('pts2', models.CharField(blank=True, max_length=20)),
                ('dano2', models.CharField(blank=True, max_length=100)),
                ('atk3', models.CharField(blank=True, max_length=100)),
                ('pts3', models.CharField(blank=True, max_length=20)),
                ('dano3', models.CharField(blank=True, max_length=100)),
                ('habilidades', models.TextField(blank=True)),
                ('pericias', models.TextField(blank=True)),
                ('vantagens', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fichas/')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rolagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expressao', models.CharField(max_length=100)),
                ('resultado', models.JSONField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolagens', to='fichas.ficha')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
