# Generated by Django 6.0.4 on 2026-05-01 03:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='criada_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campanha',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campanha',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='campanhas_como_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ficha',
            name='campanha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='fichas.campanha'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='mestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanhas_como_mestre', to=settings.AUTH_USER_MODEL),
        ),
    ]
