# Generated by Django 6.0.4 on 2026-05-01 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_campanha_criada_em_campanha_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='bonus_carisma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='bonus_constituicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='bonus_destreza',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='bonus_forca',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='bonus_inteligencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='bonus_sabedoria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='carga_max',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ficha',
            name='classe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ficha',
            name='defesa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='energia_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='formula_defesa',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='formula_energia',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='formula_sanidade',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='formula_vida',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ficha',
            name='poderes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='sanidade_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ficha',
            name='vida_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rolagem',
            name='contexto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='CombateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Combate', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('turno_atual', models.IntegerField(default=0)),
                ('rodada', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combates', to='fichas.campanha')),
            ],
        ),
        migrations.CreateModel(
            name='Criatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='criaturas/')),
                ('nivel', models.IntegerField(default=1)),
                ('valor_desafio', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('forca', models.IntegerField(default=0)),
                ('destreza', models.IntegerField(default=0)),
                ('constituicao', models.IntegerField(default=0)),
                ('inteligencia', models.IntegerField(default=0)),
                ('sabedoria', models.IntegerField(default=0)),
                ('carisma', models.IntegerField(default=0)),
                ('vida_max', models.IntegerField(default=0)),
                ('vida', models.IntegerField(default=0)),
                ('armadura', models.IntegerField(default=0)),
                ('defesa', models.IntegerField(default=0)),
                ('atk1', models.CharField(blank=True, max_length=100)),
                ('dano1', models.CharField(blank=True, max_length=50)),
                ('atk2', models.CharField(blank=True, max_length=100)),
                ('dano2', models.CharField(blank=True, max_length=50)),
                ('habilidades', models.TextField(blank=True)),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criaturas', to='fichas.campanha')),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('arma', 'Arma'), ('armadura', 'Armadura'), ('consumivel', 'Consumível'), ('ferramenta', 'Ferramenta'), ('misc', 'Misc')], default='misc', max_length=20)),
                ('quantidade', models.IntegerField(default=1)),
                ('peso', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dano', models.CharField(blank=True, max_length=50)),
                ('bonus_ataque', models.IntegerField(default=0)),
                ('bonus_defesa', models.IntegerField(default=0)),
                ('descricao', models.TextField(blank=True)),
                ('modificacoes', models.TextField(blank=True)),
                ('maldicoes', models.TextField(blank=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fichas.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipanteCombate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_override', models.CharField(blank=True, max_length=100)),
                ('iniciativa', models.IntegerField(default=0)),
                ('vida_atual', models.IntegerField(default=0)),
                ('vida_max', models.IntegerField(default=0)),
                ('derrotado', models.BooleanField(default=False)),
                ('combate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='fichas.combatesession')),
                ('criatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fichas.criatura')),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fichas.ficha')),
            ],
            options={
                'ordering': ['-iniciativa'],
            },
        ),
    ]
